version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test
      - echo "Verificando archivo de junit:"
      - ls -la reports || true
      - cat reports/junit.xml || true

reports:
  cobertura:
    files:
      - coverage/lcov.info
    file-format: LCOV
  pruebas:
    files:
      - reports/junit.xml
    file-format: JUNITXML

artifacts:
  files:
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - reports/junit.xml
