version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  build:
    commands:
      - npm test
      - echo "📄 Verificando archivos generados..."
      - ls -la reports coverage || true
      - echo "🧪 Reporte de pruebas (JUnit):"
      - '[ -f reports/junit.xml ] && cat reports/junit.xml || echo "❌ junit.xml no encontrado"'
      - echo "📊 Reporte de cobertura (LCOV):"
      - '[ -f coverage/lcov.info ] && head -20 coverage/lcov.info || echo "❌ lcov.info no encontrado"'
      - echo "🔧 Corrigiendo encabezado TN..."
      - sed -i '1s/^TN:.*$/TN:DefaultTestName/' coverage/lcov.info
      - echo "🔍 Línea 1 del lcov.info:" && head -1 coverage/lcov.info
      - grep "^TN:" coverage/lcov.info

reports:
  pruebas:
    base-directory: .
    files:
      - reports/junit.xml
    file-format: JUNITXML
    discard-paths: no

  cobertura-lcov:
    base-directory: coverage
    files:
      - lcov.info
    file-format: LCOV
    discard-paths: no


artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
