version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  build:
    commands:
      - npm test
      - echo "=== Contenido de reports/ ==="
      - ls -la reports || echo "No existe carpeta reports"
      - echo "=== Primeras líneas de junit.xml ==="
      - cat reports/junit.xml | head || echo "No existe junit.xml"


reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no


artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
