version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --silent

      - npx npm-deprecated-check --silent current > deprecated-ndc.txt || true
      - |
        if grep -q 'DEPRECATED' deprecated-ndc.txt; then
          echo -e "\033[1;33m⚠️  Hay librerías DEPRECADAS. Ver 'deprecated-ndc.txt'.\033[0m"
        fi

      - npm outdated > outdated.txt || true
      - |
        if grep -q 'Package' outdated.txt; then
          echo -e "\033[1;33m⚠️  Hay librerías DESACTUALIZADAS. Ver 'outdated.txt'.\033[0m"
        fi

  build:
    commands:
      - npm test --silent

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
