version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci --omit=dev --silent
      - aws s3 cp s3://reportecoverage/coverage/checks.sh ./checks.sh
      - chmod +x ./checks.sh
  build:
    commands:
      - npm test --silent
      - echo "Subiendo reportes de cobertura y pruebas unitarias a S3..."
      - aws s3 cp coverage/lcov-report/ s3://reportecoverage/coverage/ppx-security-back/reporte/lcov-report/ --recursive
      - aws s3 cp coverage/lcov.info s3://reportecoverage/coverage/ppx-security-back/reporte/lcov.info
      - aws s3 cp reports/junit.xml s3://reportecoverage/coverage/ppx-security-back/reporte/junit.xml

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
