version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test
      - echo "Verificando archivos de prueba:"
      - ls -la reports coverage || true
      - cat reports/junit.xml || true
      - head -20 coverage/lcov.info || true

reports:
  pruebas:
    files:
      - reports/junit.xml
      - coverage/lcov.info
    file-format: JUNITXML  # ¡Importante! Mantén JUNITXML para los tests

artifacts:
  files:
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - reports/junit.xml
