version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --silent
      - |
        DEP_MSG=$(npx npm-deprecated-check current 2>&1 | grep -v 'Checking')
        if echo "$DEP_MSG" | grep -q 'deprecated:'; then
          echo -e "\033[1;33m⚠️  Hay librerías DEPRECADAS:\033[0m"
          echo "$DEP_MSG"
        else
          echo "✅ No se encontraron librerías deprecadas."
        fi

      - |
        OUT_MSG=$(npm outdated || true)
        if echo "$OUT_MSG" | grep -q 'Package'; then
          echo -e "\033[1;33m⚠️  Hay librerías DESACTUALIZADAS:\033[0m"
          echo "$OUT_MSG"
        else
          echo "✅ Todas las librerías están actualizadas."
        fi

  build:
    commands:
      - npm test --silent

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
