version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

      # Chequeo de librerías deprecadas (solo warning, no falla el build)
      - npm install -g npm-deprecated-check
      - echo "=== Checando librerías deprecadas ==="
      - |
        ndc current > deprecated-ndc.txt || true
        if grep -q 'DEPRECATED' deprecated-ndc.txt; then
          echo -e "\033[1;33m⚠️  Se encontraron librerías deprecadas. Revisa 'deprecated-ndc.txt' para más detalles.\033[0m"
          cat deprecated-ndc.txt
        else
          echo "✅ No se encontraron librerías deprecadas."
        fi

      # Checar librerías desactualizadas (solo warning, no falla el build)
      - echo "=== Checando librerías desactualizadas ==="
      - npm outdated > outdated.txt || true
      - if grep -q 'Package' outdated.txt; then echo -e "\033[1;33m⚠️  Se encontraron librerías desactualizadas. Revisa 'outdated.txt' para más detalles.\033[0m"; fi

  build:
    commands:
      - npm test
      - echo "=== Contenido de reports/ ==="
      - ls -la reports || echo "No existe carpeta reports"
      - echo "=== Primeras líneas de junit.xml ==="
      - cat reports/junit.xml | head || echo "No existe junit.xml"

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
