version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - echo "🔍 Verificando librerías deprecadas..."
      - npm ls deprecated > deprecated.txt || true
      - cat deprecated.txt
      - if grep -q 'deprecated' deprecated.txt; then echo "❌ Se encontraron librerías deprecadas. Revisa 'deprecated.txt' para más detalles."; exit 1; fi
      - echo "🔍 Verificando librerías desactualizadas..."
      - npm outdated > outdated.txt || true
      - cat outdated.txt
      - if grep -q 'Package' outdated.txt; then echo "⚠️ Se encontraron librerías desactualizadas. Revisa 'outdated.txt' para más detalles."; exit 1; fi

  build:
    commands:
      - npm test
      - echo "📁 Contenido del directorio 'reports/':"
      - ls -la reports || echo "⚠️ El directorio 'reports' no existe."
      - echo "📄 Primeras líneas de 'junit.xml':"
      - cat reports/junit.xml | head || echo "⚠️ El archivo 'junit.xml' no existe."

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
