version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --omit=dev --silent
      - chmod +x ci-checks.sh
      - ./ci-checks.sh
  build:
    commands:
      - |
        if [ "$RUN_TESTS" = "true" ]; then
          npm test --silent
        else
          echo "ℹ️ Saltando tests"
        fi

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
