version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test
      - echo "--- Verificando cobertura ---"
      - cat coverage/lcov.info | head -20 || echo "No hay lcov.info"

reports:
  cobertura:
    files:
      - coverage/lcov.info
    file-format: LCOV

artifacts:
  files:
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
