version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔄 Instalando dependencias..."
      - npm ci --silent

      - echo "🔍 Verificando librerías deprecadas..."
      - |
        npm ls deprecated --json > deprecated.json || true
        if grep -q '"deprecated":' deprecated.json; then
          echo "❌ Se encontraron librerías deprecadas. Revisa 'deprecated.json' para más detalles."
          exit 1
        fi

      - echo "🔍 Verificando librerías desactualizadas..."
      - |
        npm outdated --json > outdated.json || true
        if [ -s outdated.json ]; then
          echo "⚠️ Se encontraron librerías desactualizadas. Revisa 'outdated.json' para más detalles."
          exit 1
        fi

  build:
    commands:
      - echo "🧪 Ejecutando pruebas..."
      - npm test
      - echo "📁 Verificando directorio 'reports/'..."
      - |
        if [ -d reports ]; then
          echo "✅ El directorio 'reports/' existe."
        else
          echo "⚠️ El directorio 'reports/' no existe."
        fi
      - echo "📄 Verificando archivo 'junit.xml'..."
      - |
        if [ -f reports/junit.xml ]; then
          echo "✅ El archivo 'junit.xml' existe."
        else
          echo "⚠️ El archivo 'junit.xml' no existe."
        fi

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
