version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  build:
    commands:
      - npm test
      - echo "📄 Verificando archivos generados..."
      - ls -la reports coverage || true
      - echo "🧪 Reporte de pruebas (JUnit):"
      - '[ -f reports/junit.xml ] && cat reports/junit.xml || echo "❌ junit.xml no encontrado"'
      - echo "📊 Reporte de cobertura (LCOV):"
      - '[ -f coverage/lcov.info ] && head -20 coverage/lcov.info || echo "❌ lcov.info no encontrado"'
      - echo "🔧 Corrigiendo encabezado TN..."
      - sed -i '1iTN:DefaultTestName' coverage/lcov.info || true
      - sed -i 's/^TN:$/TN:DefaultTestName/' coverage/lcov.info || true

reports:
  pruebas:
    files:
      - reports/junit.xml
    file-format: JUNITXML
    discard-paths: no
    base-directory: .
    export-config:
      report-name: node-tests-junit
      export-path: report-pruebas

  cobertura:
    files:
      - lcov.info
    base-directory: coverage
    file-format: LCOV
    discard-paths: no
    export-config:
      report-name: node-tests-cobertura
      export-path: report-cobertura


artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
