version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

      # Verificar dependencias obsoletas
      - echo "=== Verificando dependencias obsoletas ==="
      - npm install -g npm-deprecated-check
      - ndc current --failfast

      # Verificar dependencias desactualizadas
      - echo "=== Verificando dependencias desactualizadas ==="
      - npm outdated > outdated.txt || true
      - cat outdated.txt
      - if grep -q 'Package' outdated.txt; then echo "¡Hay dependencias desactualizadas!"; exit 1; fi

      # Auditoría de seguridad
      - echo "=== Ejecutando auditoría de seguridad ==="
      - npm audit --audit-level=high
      - if [ $? -ne 0 ]; then echo "¡Vulnerabilidades de seguridad detectadas!"; exit 1; fi

  build:
    commands:
      - npm test
      - echo "=== Contenido de reports/ ==="
      - ls -la reports || echo "No existe carpeta reports"
      - echo "=== Primeras líneas de junit.xml ==="
      - cat reports/junit.xml | head || echo "No existe junit.xml"

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
