version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --silent
      - |
        NDC_RESULT="$(npx npm-deprecated-check current 2>/dev/null)"
        if echo "$NDC_RESULT" | grep -q 'WARN'; then
          echo -e "\033[1;33m⚠️  Dependencias posiblemente deprecadas encontradas:\033[0m"
          echo "$NDC_RESULT"
        else
          echo "✅ No se encontraron librerías deprecadas."
        fi
        
      - |
        OUT_MSG=$(npm outdated || true)
        if echo "$OUT_MSG" | grep -q 'Package'; then
          echo -e "\033[1;33m⚠️  Hay librerías DESACTUALIZADAS:\033[0m"
          echo "$OUT_MSG"
        else
          echo "✅ Todas las librerías están actualizadas."
        fi

  build:
    commands:
      - npm test --silent

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
