version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --silent

      # Chequeo deprecados (warning, no detiene)
      - |
        NDC_RESULT=$(npx npm-deprecated-check current 2>/dev/null)
        DEPS=$(echo "$NDC_RESULT" | awk 'f{print "\033[1;33m⚠️ " pkg "\n" $0 "\033[0m";f=0}{if($0 ~ /^ WARN  /){pkg=$0;f=1}}')
        if [ -n "$DEPS" ]; then
          echo -e "⚠️  Librerías DEPRECADAS encontradas:"
          echo -e "$DEPS"
        else
          echo "✅ No se encontraron librerías deprecadas."
        fi

      # Chequeo desactualizados (warning, no detiene)
      - |
        OUT_MSG=$(npm outdated || true)
        if echo "$OUT_MSG" | grep -q 'Package'; then
          echo -e "\033[1;33m⚠️  Hay librerías DESACTUALIZADAS:\033[0m"
          echo "$OUT_MSG"
        else
          echo "✅ Todas las librerías están actualizadas."
        fi

  build:
    commands:
      - npm test --silent

reports:
  pruebas:
    base-directory: .
    files:
      - 'reports/junit.xml'
    file-format: 'JUNITXML'

  cobertura_codigo:
    base-directory: 'coverage'
    files:
      - 'lcov-report/**/*'
      - 'clover.xml'
    file-format: 'CLOVERXML'
    discard-paths: no

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
    - dist/**
