version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test
      - echo "📄 Verificando archivos generados..."
      - ls -la reports coverage || true
      - echo "🧪 Reporte de pruebas (JUnit):"
      - cat reports/junit.xml || true
      - echo "📊 Reporte de cobertura (LCOV):"
      - head -20 coverage/lcov.info || true
      - echo "🔧 Corrigiendo TN vacío..."
      - grep -q '^TN:' coverage/lcov.info || sed -i '1iTN:DefaultTestName' coverage/lcov.info
      - sed -i 's/^TN:$/TN:DefaultTestName/' coverage/lcov.info

reports:
  pruebas:
    files:
      - reports/junit.xml
    file-format: JUNITXML

  cobertura:
    base-directory: coverage
    files:
      - lcov.info
    file-format: LCOV

artifacts:
  files:
    - reports/junit.xml
    - coverage/lcov.info
    - coverage/lcov-report/index.html
    - coverage/coverage-final.json
